INSERT INTO USER (ID, NAME, EMAIL) VALUES (10, 'Artsiom', 'art@email.com');
INSERT INTO USER (ID, NAME, EMAIL) VALUES (11, 'George', 'geo@email.com');
INSERT INTO USER (ID, NAME, EMAIL) VALUES (12, 'Nasty', 'nasty@email.com');
INSERT INTO USER (ID, NAME, EMAIL) VALUES (13, 'Pavel', 'pav@email.com');
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID) VALUES (100.0, 10);
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID) VALUES (325.0, 11);
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID) VALUES (200.0, 12);
INSERT INTO USERACCOUNT (PREPAYMENT, USER_ID) VALUES (50.0, 13);

